### ISSUE TITLE
Restore pipeline

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-texlipse/texlipse#109]
There is no check except ECA configured for the repository.

There should be at least GitHub actions configured to run `mvn verify`
"At least" because we cannot produce signed binaries on GitHub side and finally will need Jenkins build on EF side.

@turesheim we can start from GitHub pipeline, but restoring Jenkins instance on `ci.eclipse.org` is preferable. However, it could be tricky to tune it without committer rights.

**Comment by turesheim** [comment]
Thanks @ruspl-afed . I have nominated you as committer to make our work easier.

**Comment by ruspl-afed** [comment]
> @turesheim I created [HelpDesk ticket](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4338) to restore Jenkins, but cannot find you on https://gitlab.eclipse.org to mention

found you there and add to the ticket

**Comment by ruspl-afed** [comment]
Partially done, we have GitHub CI

**Comment by ruspl-afed** [comment]
This one is done
https://download.eclipse.org/texlipse/nightly/
![image](https://github.com/eclipse-texlipse/texlipse/assets/15242312/d4d9aead-5f78-4740-bbc0-1851adfe1b9c)

More improvement to be done with further tickets
