### ISSUE TITLE
Configure dash license tool

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-texlipse/texlipse#111]
[Eclipse Dash Licenses](https://github.com/eclipse/dash-licenses) tool is extremely useful to detect any problematic dependencies during PR check

**Comment by ruspl-afed** [comment]
Not so easy because of jazzy

**Comment by DE3000** [comment]
> Not so easy because of jazzy

Is jazzy a strict requirement? Can it be removed?

**Comment by ruspl-afed** [comment]
For now I disabled the actual check, this issue remains open

**Comment by ruspl-afed** [comment]
Actual check enabled with `-Ddash.fail=false`
Let's return to this during the nearest target update.
